import vladimirAva from '../../assets/img/Владимир.png'; 
import elenaAva from '../../assets/img/Елена.png'; 
import svetlanaAva from '../../assets/img/Светлана.png'; 
import { ApplyWithUser, Category, Format, Country } from '../type/type';

export const dataUserApply: ApplyWithUser[] = [
  {
    name: 'Владимир',
    userId: 1,
    participants: [],
    avatar: vladimirAva,
    category: Category.healthcare,
    format: Format.offline,
    country: Country.belarus,
    location: 'г.Минск, пр. Независимости, д.64', 
    description: 'Прошу, может кто сможет передать продукты в 1 больницу.Все расходы готов оплатить.', 
    open: true,
  },
  {
    name: 'Елена',
    userId: 1,
    participants: [],
    avatar: elenaAva,
    category: Category.emergency,
    format: Format.offline,
    country: Country.belarus,
    location: 'Ж/д вокзал Минск', 
    description: 'Rаждое воскресенье еду с дачи с полными сумками.Кто может помочь их поднести хотябы до метро...', 
    open: true,
  },
  {
    name: 'Светлана',
    userId: 1,
    participants: [],
    avatar: svetlanaAva,
    category: Category.science,
    format: Format.online,
    country: Country.belarus,    
    description: 'Вторые сутки жутко зависает комп, аж бесит...Нужна помощь в переустановке винды.', 
    open: true,
  },
  {
    name: 'Егор',
    avatar: vladimirAva,
    userId: 1,
    participants: [],
    category: Category.veterans,
    format: Format.offline,
    country: Country.russia,
    location: 'г.Москва', 
    description: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde voluptates quidem amet aperiam est
      ratione, ut nulla blanditiis. Eaque consequuntur porro blanditiis doloremque. Harum eius assumenda quasi, 
      rerum accusantium officia.`, 
    open: true,
  },
  {
    name: 'Ольга',
    avatar: elenaAva,
    userId: 1,
    participants: [],
    category: Category.people,
    format: Format.offline,
    country: Country.russia,
    location: 'г.Солнечногорск', 
    description: 'Прошу оказать содействие по сбору подписей для установки пандуса', 
    open: true,
  },
  {
    name: 'Юля',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.children,
    format: Format.offline,
    country: Country.russia,    
    description: 'нужна помощь детям сиротам: игрушки, одежда, предметы первой необходимости', 
    open: true,
  },
  {
    name: 'Денис',
    avatar: vladimirAva,
    userId: 1,
    participants: [],
    category: Category.animals,
    format: Format.offline,
    country: Country.ukraine,
    location: 'г.Киев', 
    description: 'Возьмите пожалуйста собаку на передержку, буквально на два дня', 
    open: true,
  },
  {
    name: 'Саша',
    avatar: elenaAva,
    userId: 1,
    participants: [],
    category: Category.nature,
    format: Format.offline,
    country: Country.ukraine,
    location: 'г.Одесса', 
    description: 'Ищу добровольцев убрать городской парк', 
    open: true,
  },
  {
    name: 'Юля',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.education,
    format: Format.online,
    country: Country.ukraine,    
    description: 'Не понимаю задачку по математике', 
    open: true,
  },
  {
    name: 'Даша',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.else,
    format: Format.offline,
    country: Country.russia, 
    location: 'г.Гданьск',   
    description: 'Нужно машину помыть', 
    open: true,
  },
  {
    name: 'Виталик',
    avatar: vladimirAva,
    userId: 1,
    participants: [],
    category: Category.veterans,
    format: Format.offline,
    country: Country.belarus,
    location: 'д.Табуны', 
    description: 'Нужно починить забор соседу пенсионеру', 
    open: true,
  },
  {
    name: 'Фаина',
    avatar: elenaAva,
    userId: 1,
    participants: [],
    category: Category.veterans,
    format: Format.offline,
    country: Country.ukraine,
    location: 'г.Одесса', 
    description: 'Люди добрые, помогите собрать урожай, совсем старая стала.', 
    open: true,
  },
  {
    name: 'Зоя',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.healthcare,
    format: Format.offline,
    country: Country.ukraine,
    location: 'г.Одесса',     
    description: 'Организовываю дежурство по уходу за тяжелобольными', 
    open: true,
  },
  {
    name: 'Петя',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.healthcare,
    format: Format.offline,
    country: Country.ukraine, 
    location: 'г.Харьков',    
    description: 'Сбор вторсырья', 
    open: false,
  },
  {
    name: 'Анатолий',
    avatar: svetlanaAva,
    userId: 1,
    participants: [],
    category: Category.healthcare,
    format: Format.offline,
    country: Country.ukraine, 
    location: 'г.Львов',    
    description: 'Сбор вторсырья', 
    open: false,
  },  
];